apiVersion: v2
name: oneblock
description: A Helm chart for oneblock.ai
type: application
version: 0.0.1
appVersion: "0.0.1-dev"
keywords:
- LLMOps
- Cloud-native LLMOps
home: https://github.com/oneblock-ai/oneblock
sources:
- https://github.com/oneblock-ai/oneblock
dependencies:
- name: kuberay-operator
  version: "1.0.0"
  repository: "https://ray-project.github.io/kuberay-helm"
  condition: kuberay-operator.enabled
  tags:
  - ml-framework
  - ray.io
- name: redis
  version: 18.6.2
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
  tags:
  - redis
- name: gpu-operator
  version: 23.9.1
  repository: https://helm.ngc.nvidia.com/nvidia
  condition: gpu-operator.enabled
  tags:
  - gpu-operator
  - nvidia
- name: volcano
  version: 1.8.2
  repository: https://volcano-sh.github.io/helm-charts
  condition: volcano.enabled
  tags:
  - gang-scheduling
