oneblock:
  apiserver:
    replicas: 1
    image:
      repository: ghcr.io/oneblock-ai/oneblock
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "latest"

    service:
      type: NodePort
      ## Specify the port of HTTPs endpoint.
      ## defaults to "8443".
      httpsPort: 8443
      nodePort: 30443
      profile: 6060

      ## Specify the port of HTTP endpoint,
      ## this port will be closed if set to 0.
      ## defaults to "0".
      httpPort: 0
  webhook:
    replicas: 1
    image:
      repository: ghcr.io/oneblock-ai/oneblock-webhook
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "latest"

    service:
      type: ClusterIP
      # specify the webhook port
      httpsPort: 8444
      profile: 6060

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Automatically mount a ServiceAccount's API credentials?
    automount: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: &oneblockServiceAccountName "oneblock-cluster-admin"

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

kuberay-operator:
  enabled: true
  image:
    repository: kuberay/operator
    tag: nightly
    pullPolicy: Always
  batchScheduler:
    enabled: true
  serviceAccount:
    create: false
    name: *oneblockServiceAccountName

redis:
  enabled: true
  image:
    repository: bitnami/redis
    tag: 7.2.3-debian-11-r2
  master:
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
      - ReadWriteOnce
      size: 5Gi
  replica:
    replicaCount: 3
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
      - ReadWriteOnce
      size: 5Gi
  auth:
    enabled: true
    sentinel: true
    password: ""

gpu-operator:
  enable: true

volcano:
  enabled: true
