apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oneblock.fullname" . }}-webhook
  labels:
    {{- include "oneblock.webhookLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.oneblock.webhook.replicas }}
  selector:
    matchLabels:
      {{- include "oneblock.webhookSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.oneblock.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oneblock.webhookLabels" . | nindent 8 }}
 {{- with .Values.oneblock.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.oneblock.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "oneblock.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.oneblock.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}-webhook
        securityContext:
            {{- toYaml .Values.oneblock.securityContext | nindent 12 }}
        image: "{{ .Values.oneblock.webhook.image.repository }}:{{ .Values.oneblock.webhook.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.oneblock.apiserver.image.pullPolicy }}
        ports:
        - name: webhook-https
          containerPort: {{ .Values.oneblock.webhook.service.httpsPort }}
          protocol: TCP
        - name: profile
          containerPort: {{ .Values.oneblock.webhook.service.profile }}
          protocol: TCP
        resources:
            {{- toYaml .Values.oneblock.resources | nindent 12 }}
          {{- with .Values.oneblock.volumeMounts }}
        volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.oneblock.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.oneblock.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.oneblock.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.oneblock.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
