apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-cluster-admin
  labels:
    {{- include "oneblock.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin # grant the oneblock with full cluster admin permission
subjects:
- kind: ServiceAccount
  name: {{ include "oneblock.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
