apiVersion: v1
kind: Service
metadata:
  name: {{ include "oneblock.fullname" . }}-expose
  labels:
    {{- include "oneblock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.oneblock.apiserver.service.type }}
  ports:
    - port: {{ .Values.oneblock.apiserver.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
{{ if eq .Values.oneblock.apiserver.service.type "NodePort" }}
      nodePort: {{ .Values.oneblock.apiserver.service.nodePort }}
{{ end }}
  selector:
    {{- include "oneblock.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oneblock.fullname" . }}-webhook
  labels:
    {{- include "oneblock.webhookLabels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: {{ .Values.oneblock.webhook.service.httpsPort }} # keep the port same as what's specified in the webhook cmd.
      protocol: TCP
      name: webhook-https
  selector:
    {{- include "oneblock.webhookSelectorLabels" . | nindent 4 }}
