{{- if .Values.oneblock.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oneblock.serviceAccountName" . }}
  labels:
    {{- include "oneblock.labels" . | nindent 4 }}
  {{- with .Values.oneblock.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.oneblock.serviceAccount.automount }}
{{- end }}
