apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: ray-cluster-default
  annotations:
    ml.oneblock.ai/expose-svc: "true" # expose the Ray dashboard service to the public via nodePort
    ml.oneblock.ai/ray-cluster-enable-gcs: "false" # enabled GCS fault tolerance
spec:
  rayVersion: '2.9.0' # should match the Ray version in the image of the containers
  headGroupSpec:
    # The `rayStartParams` are used to configure the `ray start` command.
    # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
    # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
    rayStartParams:
      dashboard-host: '0.0.0.0'
    template:
      spec:
        containers:
        - name: ray-head
          image: rayproject/ray:2.9.0
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          ports:
          - containerPort: 6379
            name: gcs-server
          - containerPort: 8265 # Ray dashboard
            name: dashboard
          - containerPort: 10001
            name: client
