apiVersion: ml.oneblock.ai/v1
kind: Notebook
metadata:
  name: nb-code-server
  namespace: default
  labels:
    ml.oneblock.ai/notebook-type: code-server
spec:
  serviceType: NodePort
  template:
    spec:
      containers:
      - image: 	kubeflownotebookswg/codeserver-python:v1.8.0
        name: nb-code-server
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
        volumeMounts:
        - mountPath: /home/jovyan
          name: test-vol
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: test-vol
        persistentVolumeClaim:
          claimName: nb-code-server
      - emptyDir:
          medium: Memory
        name: dshm
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nb-code-server
  namespace: default
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
