apiVersion: ml.oneblock.ai/v1
kind: Notebook
metadata:
  name: nb-code-server
  namespace: default
  labels:
    ml.oneblock.ai/notebook-type: code-server
spec:
  template:
    spec:
      containers:
      - image: 	kubeflownotebookswg/codeserver-python:v1.8.0
        name: nb-code-server
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
        volumeMounts:
        - mountPath: /home/jovyan
          name: test-vol
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: test-vol
        persistentVolumeClaim:
          claimName: nb-code-server # keep the name to be consistent with the spec.volumes name
      - emptyDir:
          medium: Memory
        name: dshm
  volumes:
  - name: nb-code-server
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
