apiVersion: ml.oneblock.ai/v1
kind: Notebook
metadata:
  name: nb-jupyter
  namespace: default
  labels:
    ml.oneblock.ai/notebook-type: jupyter
spec:
  serviceType: NodePort
  template:
    spec:
      containers:
      - image: kubeflownotebookswg/jupyter-scipy:v1.8.0
        name: nb-jupyter
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
        volumeMounts:
        - mountPath: /home/jovyan
          name: test-vol
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: test-vol
        persistentVolumeClaim:
          claimName: nb-jupyter # keep the name to be consistent with the spec.volumes name
      - emptyDir:
          medium: Memory
        name: dshm
  volumes:
  - name: nb-jupyter
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
