name: main-release

concurrency:
  group: main-release
  cancel-in-progress: true

on:
  push:
    branches:
    - main

permissions:
  contents: write
  packages: write

jobs:
  main-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: make controller-gen
    - run: make test
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --clean --snapshot
      env:
        # GitHub sets this automatically
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OB_REPO: ${{ vars.OB_REPO || 'ghcr.io/oneblock-ai' }}
    - name: Push Latest(main) Docker Images
      run: |
        VERSION=v$(cat dist/metadata.json | jq -r .version)
        IMAGES=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep "$VERSION")
        for i in ${IMAGES}; do
          docker push $i
        done
        docker manifest create ${{ env.OB_REPO }}/oneblock:latest ${IMAGES}
        docker manifest push ${{ env.OB_REPO }}/oneblock:latest
      env:
        OB_REPO: ${{ vars.OB_REPO || 'ghcr.io/oneblock-ai' }}
    - name: Failure Slack Notification
      if: failure()
      id: slack-failure
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: "${{ secrets.SLACK_BOT_FAILURE_CHANNEL }}"
        slack-message: "❌ Main-Release failed: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
